openapi: '3.1.0'
info:
  title: Lumen Example
  version: '1.0'
servers:
  - url: http://localhost/
tags:
  - name: Server info
    description: Server information endpoints
paths:
  /:
    get:
      tags:
        - Server info
      responses:
        '200':
          description: Lumen version